platform: linux 

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: rr_git

  
outputs:
  - name: resource-app
  
run:
 path: sh
 args: ["rr_git/ci/build.sh"]
